import { createHash, randomBytes } from "node:crypto"
import { chmod, lstat, mkdir, open, readFile, readlink, readdir, rename, rm, symlink } from "node:fs/promises"
import { dirname, join } from "node:path"
import { CliError } from "./errors"
import { createJournal, persistJournal, persistPreimage, readJournal, transitionJournal, type FileState, type Journal, type JournalMutation, type JournalPhase } from "./journal"
import { ensureManagedRoot, managedRoot, type OwnershipRecord } from "./ownership"
import type { Dependencies } from "./runtime"

export type PlannedConfigMutation = { logicalPath: string; resolvedPath: string; bytes: Uint8Array; mode?: number }
export interface TransactionPlan { command: "setup" | "update" | "uninstall"; components: { tmux: boolean; opencode: boolean }; desiredVersion: string; previousCurrent: string | null; configMutations: readonly PlannedConfigMutation[]; migrationUnlinks?: readonly { logicalPath: string; resolvedPath: string }[]; ownership?: OwnershipRecord; versionActivation?: { stagingPath: string }; uninstall?: { tombstoneVersions: boolean; removeCurrent: boolean; removeOwnership: boolean } }
const missing = (error: unknown) => typeof error === "object" && error !== null && "code" in error && (error as { code?: string }).code === "ENOENT"
const hash = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex")
const absent: FileState = { type: "absent", sha256: null, mode: null }
async function state(path: string): Promise<FileState> { try { const entry = await lstat(path); if (entry.isSymbolicLink()) { const target = await readlink(path); return { type: "symlink", sha256: hash(new TextEncoder().encode(target)), mode: entry.mode & 0o777, target } } if (entry.isDirectory()) return { type: "directory", sha256: null, mode: entry.mode & 0o777 }; if (!entry.isFile()) throw new CliError("E_RECOVERY"); return { type: "file", sha256: hash(await readFile(path)), mode: entry.mode & 0o777 } } catch (error) { if (missing(error)) return absent; throw error } }
function same(left: FileState, right: FileState) { return left.type === right.type && left.sha256 === right.sha256 && left.mode === right.mode && left.target === right.target }
function temporary(path: string, deps: Dependencies, attempt: number) { return join(dirname(path), `.${path.split("/").pop()}.${Buffer.from(deps.randomBytes?.(8) ?? randomBytes(8)).toString("hex")}.${attempt}`) }
async function syncParent(path: string) { const parent = await open(dirname(path), "r"); try { await parent.sync() } finally { await parent.close() } }
async function stageBytes(path: string, bytes: Uint8Array, mode: number, deps: Dependencies) { await mkdir(dirname(path), { recursive: true, mode: 0o700 }); for (let attempt = 0; ; attempt += 1) { const temp = temporary(path, deps, attempt); try { const file = await open(temp, "wx", mode); try { await file.writeFile(bytes); await chmod(temp, mode); await file.sync() } finally { await file.close() }; return { temp, post: await state(temp) } } catch (error: any) { if (error.code !== "EEXIST") throw error } } }
async function stageSymlink(path: string, target: string, deps: Dependencies) { await mkdir(dirname(path), { recursive: true, mode: 0o700 }); for (let attempt = 0; ; attempt += 1) { const temp = temporary(path, deps, attempt); try { await symlink(target, temp); return { temp, post: await state(temp) } } catch (error: any) { if (error.code !== "EEXIST") throw error } } }
async function publish(path: string, temp: string, expected: FileState) { if (!same(await state(path), expected)) throw new CliError("E_RECOVERY"); await rename(temp, path); await syncParent(path) }
function fault(deps: Dependencies, phase: JournalPhase, boundary: "before" | "after") { if (deps.faultPhase?.phase === phase && deps.faultPhase.boundary === boundary) throw new Error(`fault:${phase}:${boundary}`) }
function signal(deps: Dependencies) { if (deps.signal) throw new CliError(`E_SIGNAL_${deps.signal}`) }
function crashMutation(deps: Dependencies, operation: "current" | "config" | "ownership", occurrence: number, boundary: "intent" | "published" | "applied") { if (deps.crashMutation?.operation === operation && deps.crashMutation.occurrence === occurrence && deps.crashMutation.boundary === boundary) throw new Error("E_CRASH") }
async function phase(journal: Journal, next: JournalPhase, deps: Dependencies) { fault(deps, next, "before"); await transitionJournal(journal, next, deps); if (deps.crashPhase === next) throw new Error("E_CRASH"); fault(deps, next, "after") }
async function capture(path: string, root: string, id: string, deps: Dependencies): Promise<{ pre: FileState; preimage: string | null }> { const pre = await state(path); if (pre.type !== "file") return { pre, preimage: null }; const preimage = join("preimages", `${hash(new TextEncoder().encode(path))}.bin`); await persistPreimage(root, id, preimage, await readFile(path), deps); return { pre, preimage } }
async function record(journal: Journal, mutation: Omit<JournalMutation, "applied">, deps: Dependencies) { const recorded = { ...mutation, applied: false }; journal.mutations.push(recorded); await persistJournal(journal, deps); return recorded }
async function markApplied(journal: Journal, mutation: JournalMutation, deps: Dependencies) { mutation.applied = true; await persistJournal(journal, deps) }
async function reverse(mutation: JournalMutation, root: string, journalId: string, deps: Dependencies) { const current = await state(mutation.resolvedPath); if (same(current, mutation.pre)) return; if (!same(current, mutation.post)) throw new CliError("E_RECOVERY"); if (mutation.pre.type === "absent") { await rm(mutation.resolvedPath, { recursive: true, force: true }); await syncParent(mutation.resolvedPath); return } if (mutation.pre.type === "directory" && mutation.backupPath) { if (!same(await state(mutation.backupPath), mutation.pre)) throw new CliError("E_RECOVERY"); await rename(mutation.backupPath, mutation.resolvedPath); await syncParent(mutation.resolvedPath); return } if (mutation.pre.type === "symlink") { await rm(mutation.resolvedPath, { force: true }); await symlink(mutation.pre.target!, mutation.resolvedPath); await syncParent(mutation.resolvedPath); return } if (mutation.pre.type === "file" && mutation.preimage) { const staged = await stageBytes(mutation.resolvedPath, await readFile(join(root, "transactions", journalId, mutation.preimage)), mutation.pre.mode!, deps); await publish(mutation.resolvedPath, staged.temp, mutation.post); return } throw new CliError("E_RECOVERY") }
export async function rollback(journal: Journal, deps: Dependencies): Promise<void> { const root = await managedRoot(deps.env); for (const mutation of [...journal.mutations].reverse()) await reverse(mutation, root, journal.id, deps) }
export async function recoverIncomplete(root: string, deps: Dependencies): Promise<void> { let ids: string[]; try { ids = await readdir(join(root, "transactions")) } catch (error) { if (missing(error)) return; throw error }; for (const id of ids) { if (id === "lock") continue; const journal = await readJournal(root, id, deps); if (journal && journal.phase !== "complete") { await rollback(journal, deps); await rm(join(root, "transactions", id), { recursive: true, force: true }) } } }
async function mutate(journal: Journal, mutation: Omit<JournalMutation, "applied">, temp: string, occurrence: number, deps: Dependencies) { const recorded = await record(journal, mutation, deps); crashMutation(deps, mutation.operation as "current" | "config" | "ownership", occurrence, "intent"); await publish(mutation.resolvedPath, temp, mutation.pre); crashMutation(deps, mutation.operation as "current" | "config" | "ownership", occurrence, "published"); await markApplied(journal, recorded, deps); crashMutation(deps, mutation.operation as "current" | "config" | "ownership", occurrence, "applied") }
async function removeMutation(journal: Journal, mutation: Omit<JournalMutation, "applied">, occurrence: number, deps: Dependencies) { const recorded = await record(journal, mutation, deps); crashMutation(deps, mutation.operation as "current" | "config" | "ownership", occurrence, "intent"); if (!same(await state(mutation.resolvedPath), mutation.pre)) throw new CliError("E_RECOVERY"); await rm(mutation.resolvedPath, { recursive: false, force: true }); await syncParent(mutation.resolvedPath); crashMutation(deps, mutation.operation as "current" | "config" | "ownership", occurrence, "published"); await markApplied(journal, recorded, deps); crashMutation(deps, mutation.operation as "current" | "config" | "ownership", occurrence, "applied") }
async function moveMutation(journal: Journal, mutation: Omit<JournalMutation, "applied">, from: string, occurrence: number, deps: Dependencies) { const recorded = await record(journal, mutation, deps); crashMutation(deps, mutation.operation as "current" | "config" | "ownership", occurrence, "intent"); if (!same(await state(mutation.resolvedPath), mutation.pre)) throw new CliError("E_RECOVERY"); await rename(from, mutation.resolvedPath); await syncParent(mutation.resolvedPath); crashMutation(deps, mutation.operation as "current" | "config" | "ownership", occurrence, "published"); await markApplied(journal, recorded, deps); crashMutation(deps, mutation.operation as "current" | "config" | "ownership", occurrence, "applied") }
async function tombstoneMutation(journal: Journal, mutation: Omit<JournalMutation, "applied">, occurrence: number, deps: Dependencies) { const recorded = await record(journal, mutation, deps); crashMutation(deps, "current", occurrence, "intent"); if (!same(await state(mutation.resolvedPath), mutation.pre) || !mutation.backupPath) throw new CliError("E_RECOVERY"); await rename(mutation.resolvedPath, mutation.backupPath); await syncParent(mutation.resolvedPath); crashMutation(deps, "current", occurrence, "published"); await markApplied(journal, recorded, deps); crashMutation(deps, "current", occurrence, "applied") }
export async function executeTransaction(plan: TransactionPlan, deps: Dependencies): Promise<void> {
  const root = await managedRoot(deps.env); await ensureManagedRoot(root); await recoverIncomplete(root, deps); signal(deps)
  const id = Buffer.from(deps.randomBytes?.(16) ?? randomBytes(16)).toString("hex"), journal = createJournal({ id, command: plan.command, packageVersion: deps.executingVersion, previousCurrent: plan.previousCurrent, components: plan.components }); await persistJournal(journal, deps)
  try {
    fault(deps, "prepared", "before"); if (deps.crashPhase === "prepared") throw new Error("E_CRASH"); fault(deps, "prepared", "after")
    const version = join(root, "versions", plan.desiredVersion)
    if (plan.uninstall?.tombstoneVersions) { const tombstone = join(root, "transactions", id, "tombstone", "versions"), source = join(root, "versions"), pre = await state(source); if (pre.type !== "directory") throw new CliError("E_OWNERSHIP"); await mkdir(dirname(tombstone), { recursive: true, mode: 0o700 }); await tombstoneMutation(journal, { operation: "tombstone", logicalPath: source, resolvedPath: source, pre, post: absent, preimage: null, backupPath: tombstone }, 1, deps) }
    else if (plan.versionActivation) { const pre = await state(version); if (pre.type !== "absent") throw new CliError("E_RECOVERY"); await moveMutation(journal, { operation: "version", logicalPath: version, resolvedPath: version, pre, post: await state(plan.versionActivation.stagingPath), preimage: null }, plan.versionActivation.stagingPath, 1, deps) }
    else if (plan.command !== "uninstall") await mkdir(version, { recursive: true, mode: 0o700 })
    await phase(journal, "version_staged", deps); signal(deps)
    const staged = await Promise.all(plan.configMutations.map(async mutation => ({ mutation, ...await capture(mutation.resolvedPath, root, id, deps) }))); await phase(journal, "configs_staged", deps)
    const current = join(root, "current"), currentPre = await state(current), target = `versions/${plan.desiredVersion}`
    if (plan.uninstall?.removeCurrent) await removeMutation(journal, { operation: "current", logicalPath: current, resolvedPath: current, pre: currentPre, post: absent, preimage: null }, 1, deps)
    else { const stagedCurrent = await stageSymlink(current, target, deps); await mutate(journal, { operation: "current", logicalPath: current, resolvedPath: current, pre: currentPre, post: stagedCurrent.post, preimage: null }, stagedCurrent.temp, 1, deps) }
    await phase(journal, "current_switched", deps)
    for (const [index, item] of staged.entries()) { const stagedFile = await stageBytes(item.mutation.resolvedPath, item.mutation.bytes, item.mutation.mode ?? (item.pre.mode ?? 0o600), deps); await mutate(journal, { operation: "config", logicalPath: item.mutation.logicalPath, resolvedPath: item.mutation.resolvedPath, pre: item.pre, post: stagedFile.post, preimage: item.preimage }, stagedFile.temp, index + 1, deps) }
    for (const [index, item] of (plan.migrationUnlinks ?? []).entries()) { const pre = await state(item.logicalPath); if (pre.type !== "symlink") throw new CliError("E_CONFIG_CONFLICT"); await removeMutation(journal, { operation: "config", logicalPath: item.logicalPath, resolvedPath: item.logicalPath, pre, post: absent, preimage: null }, staged.length + index + 1, deps) }
    if (deps.collisionAfterMutation && journal.mutations.length) { await rm(journal.mutations.at(-1)!.resolvedPath, { force: true }); throw new CliError("E_RECOVERY") }; await phase(journal, "configs_committed", deps); signal(deps)
    const ownershipPath = join(root, "state", "ownership.json"), ownershipCapture = await capture(ownershipPath, root, id, deps)
    if (plan.uninstall?.removeOwnership) await removeMutation(journal, { operation: "ownership", logicalPath: ownershipPath, resolvedPath: ownershipPath, pre: ownershipCapture.pre, post: absent, preimage: ownershipCapture.preimage }, 1, deps)
    else { const ownership: OwnershipRecord = plan.ownership ?? { schemaVersion: 1, packageVersion: deps.executingVersion, releaseVersion: plan.desiredVersion, archive: { target: "", sha256: "" }, files: [], currentTarget: target, components: { tmux: null, opencode: null }, migrations: [] }, stagedOwnership = await stageBytes(ownershipPath, new TextEncoder().encode(JSON.stringify(ownership)), 0o600, deps); await mutate(journal, { operation: "ownership", logicalPath: ownershipPath, resolvedPath: ownershipPath, pre: ownershipCapture.pre, post: stagedOwnership.post, preimage: ownershipCapture.preimage }, stagedOwnership.temp, 1, deps) }
    await phase(journal, "ownership_committed", deps)
    await phase(journal, "complete", deps); await rm(join(root, "transactions", id), { recursive: true, force: true })
  } catch (error) { if (error instanceof Error && error.message === "E_CRASH") throw error; try { await rollback(journal, deps); await rm(join(root, "transactions", id), { recursive: true, force: true }) } catch (rollbackError) { throw rollbackError } throw error }
}
