import { createHash, randomBytes } from "node:crypto"
import { chmod, lstat, mkdir, open, readFile, readlink, readdir, rename, rm, symlink, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { CliError } from "./errors"
import { createJournal, persistJournal, readJournal, transitionJournal, type FileState, type Journal, type JournalMutation, type JournalPhase } from "./journal"
import { ensureManagedRoot, managedRoot, readOwnership, type OwnershipRecord } from "./ownership"
import type { Dependencies } from "./runtime"

export type PlannedConfigMutation = { logicalPath: string; resolvedPath: string; bytes: Uint8Array; mode?: number }
export interface TransactionPlan { command: "setup" | "update" | "uninstall"; components: { tmux: boolean; opencode: boolean }; desiredVersion: string; previousCurrent: string | null; configMutations: readonly PlannedConfigMutation[] }
const missing = (error: unknown) => typeof error === "object" && error !== null && "code" in error && (error as { code?: string }).code === "ENOENT"
const hash = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex")
const absent: FileState = { type: "absent", sha256: null, mode: null }
async function state(path: string): Promise<FileState> { try { const entry = await lstat(path); if (entry.isSymbolicLink()) return { type: "symlink", sha256: hash(new TextEncoder().encode(await readlink(path))), mode: entry.mode & 0o777, target: await readlink(path) }; if (entry.isDirectory()) return { type: "directory", sha256: null, mode: entry.mode & 0o777 }; if (!entry.isFile()) throw new CliError("E_RECOVERY"); return { type: "file", sha256: hash(await readFile(path)), mode: entry.mode & 0o777 } } catch (error) { if (missing(error)) return absent; throw error } }
function same(left: FileState, right: FileState) { return left.type === right.type && left.sha256 === right.sha256 && left.mode === right.mode && left.target === right.target }
async function atomicBytes(path: string, bytes: Uint8Array, mode: number, deps: Dependencies) { await mkdir(dirname(path), { recursive: true, mode: 0o700 }); const temp = join(dirname(path), `.${path.split("/").pop()}.${Buffer.from(deps.randomBytes?.(8) ?? randomBytes(8)).toString("hex")}`); const file = await open(temp, "wx", mode); try { await file.writeFile(bytes); await file.sync() } finally { await file.close() }; if (!same(await state(path), absent)) { const current = await readFile(path); if (hash(current) === "") throw new CliError("E_RECOVERY") }; await rename(temp, path); const parent = await open(dirname(path), "r"); try { await parent.sync() } finally { await parent.close() } }
function fault(deps: Dependencies, phase: JournalPhase, boundary: "before" | "after") { if (deps.faultPhase?.phase === phase && deps.faultPhase.boundary === boundary) throw new Error(`fault:${phase}:${boundary}`) }
function signal(deps: Dependencies) { if (deps.signal) throw new CliError(`E_SIGNAL_${deps.signal}`) }
async function phase(journal: Journal, next: JournalPhase, deps: Dependencies) { fault(deps, next, "before"); await transitionJournal(journal, next, deps); if (deps.crashPhase === next) throw new Error("E_CRASH"); fault(deps, next, "after") }
async function capture(path: string, root: string, id: string): Promise<{ pre: FileState; preimage: string | null }> { const pre = await state(path); if (pre.type !== "file") return { pre, preimage: null }; const preimage = join("preimages", `${hash(new TextEncoder().encode(path))}.bin`); const place = join(root, "transactions", id, preimage); await mkdir(dirname(place), { recursive: true, mode: 0o700 }); await writeFile(place, await readFile(path), { mode: 0o600 }); return { pre, preimage } }
export async function rollback(journal: Journal, deps: Dependencies): Promise<void> { const root = await managedRoot(deps.env); for (const mutation of [...journal.mutations].reverse()) { if (!same(await state(mutation.resolvedPath), mutation.post)) throw new CliError("E_RECOVERY"); if (mutation.pre.type === "absent") await rm(mutation.resolvedPath, { recursive: true, force: true }); else if (mutation.pre.type === "symlink") { await rm(mutation.resolvedPath, { force: true }); await symlink(mutation.pre.target!, mutation.resolvedPath) } else if (mutation.pre.type === "file") { if (!mutation.preimage) throw new CliError("E_RECOVERY"); await atomicBytes(mutation.resolvedPath, await readFile(join(root, "transactions", journal.id, mutation.preimage)), mutation.pre.mode!, deps) } }
}
export async function recoverIncomplete(root: string, deps: Dependencies): Promise<void> { let ids: string[]; try { ids = await readdir(join(root, "transactions")) } catch (error) { if (missing(error)) return; throw error }; for (const id of ids) { if (id === "lock") continue; const journal = await readJournal(root, id, deps); if (journal && journal.phase !== "complete") { await rollback(journal, deps); await rm(join(root, "transactions", id), { recursive: true, force: true }) } } }
export async function executeTransaction(plan: TransactionPlan, deps: Dependencies): Promise<void> {
  const root = await managedRoot(deps.env); await ensureManagedRoot(root); await recoverIncomplete(root, deps); signal(deps)
  const id = Buffer.from(deps.randomBytes?.(16) ?? randomBytes(16)).toString("hex"), journal = createJournal({ id, command: plan.command, packageVersion: deps.executingVersion, previousCurrent: plan.previousCurrent, components: plan.components }); await persistJournal(journal, deps)
  try {
    fault(deps, "prepared", "before"); if (deps.crashPhase === "prepared") throw new Error("E_CRASH"); fault(deps, "prepared", "after")
    const version = join(root, "versions", plan.desiredVersion); if (plan.command === "uninstall") { const tombstone = join(root, "transactions", id, "tombstone"); await mkdir(tombstone, { recursive: true, mode: 0o700 }) } else await mkdir(version, { recursive: true, mode: 0o700 }); await phase(journal, "version_staged", deps); signal(deps)
    const staged = await Promise.all(plan.configMutations.map(async mutation => ({ mutation, ...await capture(mutation.resolvedPath, root, id) }))); await phase(journal, "configs_staged", deps)
    const current = join(root, "current"), old = await state(current), target = `versions/${plan.desiredVersion}`, temporary = join(root, `.current.${id}`); await symlink(target, temporary); await rename(temporary, current); journal.mutations.push({ operation: "current", logicalPath: current, resolvedPath: current, pre: old, post: await state(current), preimage: null }); await phase(journal, "current_switched", deps)
    for (const { mutation, pre, preimage } of staged) { await atomicBytes(mutation.resolvedPath, mutation.bytes, mutation.mode ?? (pre.mode ?? 0o600), deps); journal.mutations.push({ operation: "config", logicalPath: mutation.logicalPath, resolvedPath: mutation.resolvedPath, pre, post: await state(mutation.resolvedPath), preimage }) }; if (deps.collisionAfterMutation && journal.mutations.length) { await writeFile(journal.mutations.at(-1)!.resolvedPath, "collision"); throw new CliError("E_RECOVERY") }; await phase(journal, "configs_committed", deps); signal(deps)
    const ownershipPath = join(root, "state", "ownership.json"), ownershipPre = await state(ownershipPath), ownership: OwnershipRecord = { schemaVersion: 1, packageVersion: deps.executingVersion, releaseVersion: plan.desiredVersion, archive: { target: "", sha256: "" }, files: [], currentTarget: target, components: { tmux: null, opencode: null }, migrations: [] }; await atomicBytes(ownershipPath, new TextEncoder().encode(JSON.stringify(ownership)), 0o600, deps); journal.mutations.push({ operation: "ownership", logicalPath: ownershipPath, resolvedPath: ownershipPath, pre: ownershipPre, post: await state(ownershipPath), preimage: null }); await phase(journal, "ownership_committed", deps)
    await phase(journal, "complete", deps); await rm(join(root, "transactions", id), { recursive: true, force: true })
  } catch (error) { if (error instanceof Error && error.message === "E_CRASH") throw error; try { await rollback(journal, deps); await rm(join(root, "transactions", id), { recursive: true, force: true }) } catch (rollbackError) { throw rollbackError } throw error }
}
